### ISSUE TITLE
Resolve code/doc discrepancies

### ISSUE THREAD

**Issue by kwannoel** [kwannoel/urban-octo-carnival#109]
In GitLab by @fahree on Feb 9, 2021, 03:35

 - [x] 1.7 has "static safety analyses that are discharged by a theorem solver". Since this won't be part of launch, the docs shouldn't use present tense, should be rephrased or moved to "future plans". (@AlexKnauth Near-Future Plans)
 - [x] 2.1.3 code allows `!` in identifiers now, docs are behind and don't mention it, some reserved words should have `!` in them (@AlexKnauth Update docs to match code)
 - [x] 2.2 code doesn't support `data` and `type` definitions very well. This should either be fully supported by Launch, or the docs should explain their limitations, or they should be moved to "future plans", or something else I'm not sure. (@AlexKnauth Near-Future Plans)
 - [x] 2.3 `assert!` should probably be removed from the documentation or moved to "future plans" if the compile-time checks aren't implemented by launch. (@AlexKnauth Near-Future Plans)
 - [x] 2.3 `require!` "will reject the program unless it can prove that the assertion is indeed satisfiable" (@AlexKnauth Near-Future Plans)
 - [x] 2.4 compound switch patterns are not currently supported by the code in the parser, but the docs use compound patterns in the example (@AlexKnauth update grammar, @AlexKnauth update parser)
 - [x] 2.4 compound switch patterns are not currently supported by the code in the runtime, but the docs use compound patterns in the example (@AlexKnauth Water-down doc example, Near-Future Plans)
 - [x] 2.5.2 "Integers in Glow are not limited in size"  (@AlexKnauth  #110) Currently uint256, move BigInt to NFP
 - [x] 2.5.3 "escape sequences" these should probably just be added to in lexical.ss (@AlexKnauth update lexer)
 - [x] 2.5.5-6 tuples and records aren't implemented in the code in the runtime yet (@AlexKnauth Near-Future Plans)
 - [x] 2.6 `<pat>` isn't fully supported by the code in the parser yet (@AlexKnauth update grammar, @AlexKnauth update parser)
 - [x] 4.3.2.2 "In Glow, we only have BigInt-style integers" (@AlexKnauth  #110) Currently uint256, move BigInt to NFP
 - [x] Integer Section should mention NFP (@AlexKnauth  #110) Currently uint256, future BigInt

For many of these, a new "Near-Future Plans" section would be appropriate.

**Comment by kwannoel** [comment]
In GitLab by @fahree on Feb 9, 2021, 03:35

assigned to @AlexKnauth

**Comment by kwannoel** [comment]
In GitLab by @fahree on Feb 9, 2021, 03:39

There are discrepancies between our code and documentation, let's resolve them one way or another:
- [ ] Decide the semantics of Glow arithmetics wrt Int vs Nat vs UInt256: Now
- [ ] Document that it will change in the future, refer to future issue

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Feb 18, 2021, 01:02

Three tasks here:
Identify/triage and note where they are in documentation
Address the Launch related ones
Tag the non-Launch related ones for post-Launch

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 23, 2021, 03:37

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 23, 2021, 03:42

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 23, 2021, 03:45

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 23, 2021, 03:47

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 23, 2021, 03:55

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 24, 2021, 04:17

mentioned in merge request !109

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 24, 2021, 04:18

marked the task **2.1.3 code allows `!` in identifiers now, docs are behind and don't mention it, some reserved words should have `!` in them (@AlexKnauth Update docs to match code)** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 24, 2021, 04:20

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 24, 2021, 04:20

marked the task **2.5.3 "escape sequences" these should probably just be added to in lexical.ss (@AlexKnauth or @Akaa update lexer)** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 24, 2021, 04:21

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 24, 2021, 04:21

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 24, 2021, 04:21

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 00:14

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Feb 25, 2021, 00:16

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Feb 25, 2021, 00:17

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Feb 25, 2021, 00:18

marked this issue as related to #140

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Feb 25, 2021, 00:18

marked this issue as related to #110

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Feb 25, 2021, 00:29

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Feb 25, 2021, 00:31

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Feb 25, 2021, 00:31

changed the description

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:26

marked the task **1.7 has "static safety analyses that are discharged by a theorem solver". Since this won't be part of launch, the docs shouldn't use present tense, should be rephrased or moved to "future plans". (@AlexKnauth Near-Future Plans)** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:26

marked the task **2.2 code doesn't support `data` and `type` definitions very well. This should either be fully supported by Launch, or the docs should explain their limitations, or they should be moved to "future plans", or something else I'm not sure. (@AlexKnauth Near-Future Plans)** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:26

marked the task **2.3 `assert!` should probably be removed from the documentation or moved to "future plans" if the compile-time checks aren't implemented by launch. (@AlexKnauth Near-Future Plans)** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:26

marked the task **2.3 `require!` "will reject the program unless it can prove that the assertion is indeed satisfiable" (@AlexKnauth Near-Future Plans)** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:26

marked the task **2.4 compound switch patterns are not currently supported by the code in the runtime, but the docs use compound patterns in the example (@AlexKnauth Water-down doc example, Near-Future Plans)** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:26

marked the task **2.5.2 "Integers in Glow are not limited in size"  (@AlexKnauth  #110) Currently uint256, move BigInt to NFP** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:26

marked the task **2.5.5-6 tuples and records aren't implemented in the code in the runtime yet (@AlexKnauth Near-Future Plans)** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:26

marked the task **4.3.2.2 "In Glow, we only have BigInt-style integers" (@AlexKnauth  #110) Currently uint256, move BigInt to NFP** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:26

marked the task **Integer Section should mention NFP (@AlexKnauth  #110) Currently uint256, future BigInt** as completed

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 25, 2021, 14:27

mentioned in merge request !114

**Comment by kwannoel** [comment]
In GitLab by @AlexKnauth on Feb 26, 2021, 01:05

Resolved by !109 and !114, follow-up with issues #137, #110, #115, #68, and #79 for implementing the features in Near-Future Plans (and of course moving their docs to the proper places once implemented).
