### ISSUE TITLE
UI for sending tokens

### ISSUE THREAD

**Issue by kwannoel** [kwannoel/urban-octo-carnival#124]
In GitLab by @fahree on Feb 15, 2021, 23:16

* [x] Drop down menu: Select FROM address from addresses in address book that
  * [x] Are registered as having the private key on file or in a linked wallet.
  * [ ] Have tags have match the current context.
  * [ ] ... modify the context wrt to tags they are allowed to interact with.
* [x] Drop down menu: Select TO address from addresses in address book that
  * [ ] Have tags have match the current context.
  * [ ] ... modify the context wrt to tags they are allowed to interact with.
  * [x] Also option for copy/pasting an address, and/or for adding it to the address book?
* [x] Drop down menu: asset to be transferred
  * [x] Amount box: lets you specify the amount of the asset (if it's an NFT, that's 0 or 1).
  * [ ] Option to send "all at address" (minus fees below).
  * [x] Asset class may default to the "native token" for the current network.
  * [ ] Display the equivalent value in the user's unit of tax accounting (e.g. USD, CAD).
* [ ] Information only: fees and totals in both units, in thinner/greyer font
  * [ ] Display the expected associated fees and rates in all relevant units (e.g. GAS + ETH/GAS + ETH + USD).
  * [x] Display the total in the relevant units (e.g. ETH + USD).
  * [ ] Have tags have match the current context.
* [x] Step 2: can send multiple assets in one transaction, all on the same network.
  * [x] Call backend API for sending as one tx per asset
  * [x] Call backend API for sending as all assets in one tx (CANCELLED)
* [x] SEND button: only activated when all data is complete.
* [x] Talk to the local server wrt getting the data (address book, exchange rate, associated fees, executing the transaction).
* [x] Single app "send tokens" (not "from A to B"), that allows either single or multi transfers
* [x] Each asset being transferred has its own box with light separators above and below
* [ ] Each asset has its equivalent price in unit of account
* [ ] There is only one selection for the unit of account, across all assets
* [ ] If there is more than one asset, there is also a total in unit of account.
* [ ] A box to display current available assets: balances in existing asset classes + NFTs
* [x] Have a precompiled tested version that works checked in
* [ ] Nix build for gloui
* [x] make it choose first contact and first address automagically
* [x] disallow sharing addresses by default
* [x] show balance before amount selection
* [x] warn if trying to send more than available
* [x] default icon as per https://www.npmjs.com/package/@metamask/jazzicon
* [ ] if no icon selected for a contact, use the one from the first address
* [ ] let users upload icon
* [ ] send "all" feature
* [ ] recognize the secret key with or without 0x prefix
* [ ] delete contacts or addresses

Moving to other tickets
* [ ] fare: add glow list-asset-classes
* [ ] fare: add the "send all at address" functionality
* [x] fare: make glow transfer work for ERC20s as well as native tokens.
* [ ] drewc: gh-pages
* [x] fare: replace CLI calls by a JSON RPC server
* [ ] drewc: move build to GUIX instead of Nix(?)
* [x] ~~both: negotiate a schema for identities, contacts, addresses, assets, ERCxx contracts, HD wallet key paths, key access via other wallets~~ #150 
* [x] ~~both: UI for negotiating contract terms(?)~~ #105
* [x] ~~drewc: ERC20~~ #147
* [x] ~~drewc: multiple assets at once~~
* [x] ~~drewc: UI for buy-sig~~ #161
* [x] ~~drewc: UI for rps~~ #162
* [x] ~~drewc: UI for coin-flip~~ #168 
* [x] ~~drewc: UI for asset swap~~ #163
* [ ] Handle autosave: autosave drafts, but beware that any secrets must remain encrypted even in draft, etc.
* [ ] Hand over GUI to someone else so drewc can focus on gxi-on-browser?
* [ ] Have a single "contact" menu for a contact and all his addresses, in the style of Google Contacts.
* [ ] Have a notion of "unregistered contact file" that you edit, with a "save" button at the end that does the save (and maybe fails and/or offers a merge if changes have been made to the contact by some other activity?)
* [X] Have a separate field for what name to use for the currency in the currency feed, if any.
* [X] Have a tag indicating that some networks and/or currencies are for testing, not production

**Comment by kwannoel** [comment]
In GitLab by @fahree on Feb 15, 2021, 23:25

- [x] Drop down menu: Select FROM address from addresses in address book that
  - [x] Are registered as having the private key on file or in a linked wallet.
  - [x] Have tags have match the current context.
  - [x] ... modify the context wrt to tags they are allowed to interact with.
- [x] Drop down menu: Select TO address from addresses in address book that
  - [x] Have tags have match the current context.
  - [x] ... modify the context wrt to tags they are allowed to interact with.
  - [x] Also option for copy/pasting an address, and/or for adding it to the address book?
- [x] Drop down menu: asset to be transferred
  - [x] Amount box: lets you specify the amount of the asset (if it's an NFT, that's 0 or 1).
  - [x] Option to send "all at address" (minus fees below).
  - [x] Asset class may default to the "native token" for the current network.
  - [x] Display the equivalent value in the user's unit of tax accounting (e.g. USD, CAD).
- [ ] Information only: fees and totals in both units, in thinner/greyer font
  - [ ] Display the expected associated fees and rates in all relevant units (e.g. GAS + ETH/GAS + ETH + USD).
  - [ ] Display the total in the relevant units (e.g. ETH + USD).
  - [ ] Have tags have match the current context.
- [x] Step 2: can send multiple assets in one transaction, all on the same network.
  - [x] Call backend API for sending as one tx per asset
  - [x] Call backend API for sending as all assets in one tx (CANCELLED)
- [ ] SEND button: only activated when all data is complete.
- [x] Talk to the local server wrt getting the data (address book, exchange rate, associated fees, executing the transaction).
- [x] Single app "send tokens" (not "from A to B"), that allows either single or multi transfers
- [ ] Each asset being transferred has its own box with light separators above and below
- [x] Each asset has its equivalent price in unit of account
- [ ] There is only one selection for the unit of account, across all assets
- [ ] If there is more than one asset, there is also a total in unit of account.
- [ ] A box to display current available assets: balances in existing asset classes + NFTs
- [ ] Have a precompiled tested version that works checked in
- [ ] Nix build for gloui

**Comment by kwannoel** [comment]
In GitLab by @fahree on Feb 15, 2021, 23:25

assigned to @drewc

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 17, 2021, 19:21

@drewc there are a series of subtasks listed above. Please update that section and check off anything that is finished.

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 17, 2021, 23:14

https://gitlab.com/drewc/gloui

**Comment by kwannoel** [comment]
In GitLab by @fahree on Mar 17, 2021, 23:56

@fare to move these to another issue:
- [x] drewc: ERC20
- [ ] fare: add glow list-asset-classes
- [x] fare: make glow transfer work for ERC20s as well as native tokens.
- [ ] drewc: multiple assets at once
- [ ] drewc: gh-pages
- [x] fare: replace CLI calls by a JSON RPC server
- [ ] drewc: move build to GUIX instead of Nix(?)
- [ ] both: negotiate a schema for identities, contacts, addresses, assets, ERCxx contracts, HD wallet key paths, key access via other wallets
- [ ] both: UI for negotiating contract terms(?)
- [ ] drewc: UI for buy-sig
- [ ] drewc: UI for rps
- [ ] drewc: UI for coin-flip
- [ ] drewc: UI for asset swap

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 25, 2021, 02:04

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 25, 2021, 02:04

@fahree I moved all these items to the notes up top. I can't edit your comments

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 25, 2021, 02:05

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 26, 2021, 23:13

marked this issue as related to #160

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 26, 2021, 23:13

marked this issue as related to #164

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 26, 2021, 23:13

marked this issue as related to #149

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 26, 2021, 23:15

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 26, 2021, 23:15

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 26, 2021, 23:16

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 26, 2021, 23:17

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 26, 2021, 23:18

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on Mar 26, 2021, 23:19

changed the description

**Comment by kwannoel** [comment]
In GitLab by @fahree on Mar 26, 2021, 23:21

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on May 4, 2021, 02:10

@drewc is the status of these subtasks accurate? Is this ticket still open?

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 04:08

marked the task **Have tags have match the current context.** as incomplete

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 04:08

marked the task **... modify the context wrt to tags they are allowed to interact with.** as incomplete

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 04:08

marked the task **Have tags have match the current context.** as incomplete

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 04:08

marked the task **... modify the context wrt to tags they are allowed to interact with.** as incomplete

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 04:08

marked the task **Also option for copy/pasting an address, and/or for adding it to the address book?** as incomplete

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 04:08

marked the task **Option to send "all at address" (minus fees below).** as incomplete

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 04:08

marked the task **Asset class may default to the "native token" for the current network.** as incomplete

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 04:08

marked the task **Display the equivalent value in the user's unit of tax accounting (e.g. USD, CAD).** as incomplete

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 04:15

changed the description

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 05:21

changed the description

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 06:41

changed the description

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 07:52

changed the description

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 8, 2021, 08:07

changed the description

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on May 10, 2021, 23:11

@drewc can you please update the checkboxes above to reflect the latest state?

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on May 20, 2021, 19:03

@drewc after chatting with @fahree earlier, he indicated that this is delivered (at least partially). The subtasks do not seem to reflect that. Can you please outline what is left for this specific ticket, if anything?

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:11

marked the task **Asset class may default to the "native token" for the current network.** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:11

marked the task **Step 2: can send multiple assets in one transaction, all on the same network.** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:11

marked the task **SEND button: only activated when all data is complete.** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:12

marked the task **Talk to the local server wrt getting the data (address book, exchange rate, associated fees, executing the transaction).** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:12

marked the task **Single app "send tokens" (not "from A to B"), that allows either single or multi transfers** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:12

marked the task **Each asset being transferred has its own box with light separators above and below** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:12

marked the task **Have a precompiled tested version that works checked in** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:12

marked the task **make it choose first contact and first address automagically** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:12

marked the task **disallow sharing addresses by default** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:12

marked the task **show balance before amount selection** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:13

marked the task **show balance before amount selection** as incomplete

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:13

marked the task **show balance before amount selection** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:13

marked the task **warn if trying to send more than available** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:13

marked the task **default icon as per https://www.npmjs.com/package/@metamask/jazzicon** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:14

marked the task **Also option for copy/pasting an address, and/or for adding it to the address book?** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:14

marked the task **Display the total in the relevant units (e.g. ETH + USD).** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:14

marked the task **Call backend API for sending as one tx per asset** as completed

**Comment by kwannoel** [comment]
In GitLab by @drewc on May 21, 2021, 02:26

Hey,

Basically just wondering what the take is on a few.

-   Have tags have match the current context.
-  ... modify the context wrt to tags they are allowed to interact with.

We do not really have a "context", per se, unless a "contact" AKA "Rolodex
Card" is in fact a context and "tags" are, right now, just the name and
description AKA metadata of that contact.

So, this is either "complete" or needs moved to another task list and/or
needs reworded in order to meld with the actual requirements.

Beyond that the rest are right in line with the refactoring/clean up that I
will start on later today and though most are "half checked" at this point
one of the reasons for that factorization is in fact to help turn the [ / ]
's into [ X ]'s.

Let me know what you think, —drewc

**Comment by kwannoel** [comment]
In GitLab by @ApolloUnicorn on May 21, 2021, 02:34

cc @fahree

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 21, 2021, 21:22

At this point, I think we should open a new ticket with any outstanding issues.

Other items that were done:
- [X] Each asset has its equivalent price in unit of account
- [X] make it choose first contact and first address automagically
- [X] disallow sharing addresses by default
- [X] Fare to deploy on his localhost
- [X] Properly label the token name in transfer, not just "native" vs "ERC20", but "PET" vs "QASPET".
- [X] Display token name token type name, instead of "ERC20" and "Native"
- [X] show balance before amount selection
- [X] warn if trying to send more than available
- [X] show exchange rates with token-dependent parameter for the official name
- [X] show "test" icon / small text next to test networks/currencies/etc. From the network for now.
- [X] default icon as per https://www.npmjs.com/package/@metamask/jazzicon

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 21, 2021, 21:49

marked the task **Have a separate field for what name to use for the currency in the currency feed, if any.** as completed

**Comment by kwannoel** [comment]
In GitLab by @fahree on May 21, 2021, 21:49

marked the task **Have a tag indicating that some networks and/or currencies are for testing, not production** as completed
